// dialog-memory.mjs — remembers the folder a file dialog last used, shared by every yaiol Electron app.
//
// ⚠ NEVER hand-edit an app's copy — it is generated by `.common/shared/sync-shared.js`
//    from the canonical source. Edit the canonical file and re-sync.
//
// Electron 43 made `defaultPath` default to the Downloads folder when a dialog does not pass
// one, and stopped the OS restoring the last-used directory. Every "open" dialog therefore
// starts in Downloads instead of where the user was working. Passing an explicit path is the
// documented migration; this stores it, keyed per dialog, in userData so it survives a restart.

import fs from "node:fs";
import path from "node:path";
import { app } from "electron";

let cache = null;
const file = () => path.join(app.getPath("userData"), "dialog-dirs.json");

function load() {
  if (!cache) {
    try { cache = JSON.parse(fs.readFileSync(file(), "utf8")); } catch { cache = {}; }
  }
  return cache;
}

// The folder to open a dialog in, or undefined on first use (Electron then picks Downloads).
export function lastDir(key) {
  const d = load()[key];
  return d && fs.existsSync(d) ? d : undefined;
}

// Record what the user picked. Accepts a file or a folder; a file is reduced to its folder.
export function rememberDir(key, picked) {
  if (!picked) return;
  let dir = picked;
  try { if (!fs.statSync(picked).isDirectory()) dir = path.dirname(picked); } catch { return; }
  const d = load();
  if (d[key] === dir) return;
  d[key] = dir;
  try { fs.writeFileSync(file(), JSON.stringify(d, null, 2)); } catch { /* non-fatal */ }
}
