// startup-timing.mjs — main-process cold-start instrumentation, shared by every yaiol Electron app.
//
// ⚠ NEVER hand-edit an app's copy — it is generated by `.common/shared/sync-shared.js`
//    from the canonical source. Edit the canonical file and re-sync.
//
// WHY IT IS ALWAYS COMPILED IN BUT SILENT BY DEFAULT
//   `mark()` is an array push plus a Date.now() — microseconds, so the calls stay in the
//   shipped build permanently and any packaged release can be measured without a special
//   build. What users must NOT pay for is the console spam and a log file growing in their
//   userData on every launch, so `dumpStartupTiming()` writes NOTHING unless the env var
//   YAIOL_STARTUP_LOG is set:
//
//     set YAIOL_STARTUP_LOG=1 && "%LOCALAPPDATA%\Programs\<App>\<App>.exe"
//
// T0 IS THE OS PROCESS CREATION TIME, not module-load time. That is the whole point: the
// first mark then includes Electron/Chromium boot AND this app's module imports, which
// happen before any of our code can run and are usually the largest single cost.
//
// FIVE SHARED MARKS — same names in every app, so numbers are comparable across apps:
//   "electron boot + module imports" · "app.whenReady" · "express listening"
//   "BrowserWindow created" · "renderer did-finish-load"
// An app may add its own marks between them (ampl marks sqlite/schema/seeding). Keep the
// five shared names spelled exactly as above or cross-app comparison breaks.
import fs from "fs";
import path from "path";

const T0 = (typeof process.getCreationTime === "function" ? process.getCreationTime() : 0) || Date.now();
const MARKS = [];

const MAX_LOG_BYTES = 256 * 1024;   // opt-in, but never let the file grow unbounded

/** Record a phase boundary. Cheap enough to leave in shipped builds. */
export function mark(label) {
  MARKS.push([label, Math.round(Date.now() - T0)]);
}

/** True when the user asked for timings via the env var. */
export function startupTimingEnabled() {
  return !!process.env.YAIOL_STARTUP_LOG;
}

/**
 * Render the collected marks and, when enabled, print them and append them to
 * <userData>/startup-timing.log. No-op otherwise.
 *
 * @param {object}  o
 * @param {string}  o.appName      productName, for the header
 * @param {boolean} o.isDev        DEV vs PACKAGED in the header — dev numbers are NOT
 *                                 comparable (Vite dev server + unpacked node_modules)
 * @param {string}  [o.userDataPath] where to append the log; omit to only print
 */
export function dumpStartupTiming({ appName, isDev, userDataPath }) {
  if (!startupTimingEnabled()) return;

  let prev = 0;
  const rows = MARKS.map(([label, at]) => {
    const row = `${String(at).padStart(6)} ms   +${String(at - prev).padStart(5)} ms   ${label}`;
    prev = at;
    return row;
  });
  const out = [
    ``,
    `═══ ${appName} startup — ${isDev ? "DEV" : "PACKAGED"} — ${new Date().toISOString()}`,
    `  total     step     phase`,
    ...rows,
    ``,
  ].join("\n");

  console.log(out);
  if (!userDataPath) return;
  try {
    const file = path.join(userDataPath, "startup-timing.log");
    let size = 0;
    try { size = fs.statSync(file).size; } catch { /* first run */ }
    if (size > MAX_LOG_BYTES) fs.writeFileSync(file, out, "utf8");
    else fs.appendFileSync(file, out, "utf8");
  } catch { /* never let instrumentation break startup */ }
}
