// i18n-split.mjs — build step: split an app's src/i18n.js into one chunk per language.
//
// WHY
//   src/i18n.js holds every UI string in every language in ONE object. A static import puts
//   all ~50 languages in the entry chunk, so every user parses 50 translations to read one.
//   This emits src/i18n-gen/en.js + src/i18n-gen/lang/<lang>.js (one module per language) plus
//   src/i18n-gen/index.js
//   (the same public API: LANGUAGES, useT, getT — plus loadLang). English is bundled eagerly
//   because it is the fallback; every other language is fetched on demand.
//
// ⚠ src/i18n.js IS NEVER MODIFIED. It stays the single authoring source, so i18n-sort.js,
//   i18n-audit.js and the whole i18n-keys-* family keep working on the file they always did.
//
// ⚠ src/i18n-gen/ IS GENERATED — gitignored, never hand-edited, rebuilt on every `npm run build`
//   via the `prebuild` script. Edit src/i18n.js and rebuild.
//
// ⚠ THIS IS THE CANONICAL SOURCE — it is distributed by .common/shared/sync-shared.js into every
//   app as main/scripts/i18n-split.mjs, and `prebuild`/`prestart` run THAT copy. It must ship
//   inside main/ because main/ is the whole GitHub repo: a build (CI, or an external clone) has
//   no .common/ to reach into. Never hand-edit an app's copy — edit here and re-run sync-shared.
//
// Usage (from an app's main/):
//   node scripts/i18n-split.mjs .          # or with no argument — defaults to the cwd
import fs from "fs";
import path from "path";

const HEADER = `// ⚠ GENERATED by scripts/i18n-split.mjs — DO NOT EDIT, DO NOT COMMIT.
// Source of truth is src/i18n.js. Rebuilt by the app's \`prebuild\` script.
`;

// Pull out `export const NAME = { … };` / `= [ … ];` verbatim.
// ⚠ CLAUDE: this counts brackets — it does NOT look for a closing brace at column 0. ampl's
// LANG_LOCALE ends inline (`yo: "yo-NG" };`), and a column-0 terminator silently ran on to the
// next declaration and swallowed LANGUAGES whole. String literals are stripped first so a brace
// inside a translated label can't unbalance the count.
function extractExport(lines, name) {
  const start = lines.findIndex((l) => new RegExp(`^export const ${name}\\s*=`).test(l));
  if (start < 0) return null;
  let depth = 0, opened = false;
  for (let i = start; i < lines.length; i++) {
    const code = lines[i].replace(/'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|`(?:[^`\\]|\\.)*`/g, "");
    for (const ch of code) {
      if (ch === "{" || ch === "[") { depth++; opened = true; }
      else if (ch === "}" || ch === "]") depth--;
    }
    if (opened && depth === 0) return lines.slice(start, i + 1).join("\n");
  }
  return null;
}

function splitApp(mainDir, label) {
  const srcFile = path.join(mainDir, "src", "i18n.js");
  if (!fs.existsSync(srcFile)) { console.log(`SKIP  ${label} — no src/i18n.js`); return; }
  const lines = fs.readFileSync(srcFile, "utf8").split("\n");

  const tStart = lines.findIndex((l) => /^const TRANSLATIONS\s*=\s*\{/.test(l));
  if (tStart < 0) { console.log(`SKIP  ${label} — no TRANSLATIONS object`); return; }

  // Language blocks sit at exactly two-space indent; the object closes at column 0.
  const langs = {};
  let cur = null, body = [];
  for (let i = tStart + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^\};\s*$/.test(line)) break;                       // end of TRANSLATIONS
    const open = /^ {2}([A-Za-z]{2}(?:[-_][A-Za-z0-9]+)?)\s*:\s*\{\s*$/.exec(line);
    if (open && cur === null) { cur = open[1]; body = []; continue; }
    if (cur !== null && /^ {2}\},?\s*$/.test(line)) { langs[cur] = body; cur = null; continue; }
    if (cur !== null) body.push(line);
  }
  const keys = Object.keys(langs);
  if (!keys.length) { console.log(`SKIP  ${label} — no language blocks parsed`); return; }
  if (!langs.en) { console.log(`FAIL  ${label} — no 'en' block; refusing to generate`); return; }
  if (cur !== null) { console.log(`FAIL  ${label} — language block '${cur}' never closed; refusing to generate`); return; }

  // A language with far fewer keys than 'en' is worth reporting, but it is NOT a reason to
  // refuse: an untranslated key already falls back to English at runtime
  // (`lang[key] ?? base[key] ?? key`), and that is exactly what the split preserves. This is a
  // translation-coverage signal — the fix belongs in i18n-audit, not here.
  const count = (b) => b.filter((l) => /^\s{4}\w+\s*:/.test(l)).length;
  const enKeys = count(langs.en);
  const thin = keys.filter((k) => count(langs[k]) < enKeys * 0.5);
  if (thin.length) console.log(`WARN  ${label} — ${thin.length}/${keys.length} languages have <50% of 'en' keys (${enKeys}); run i18n-audit`);

  const outDir = path.join(mainDir, "src", "i18n-gen");
  fs.rmSync(outDir, { recursive: true, force: true });      // no stale language files
  fs.mkdirSync(outDir, { recursive: true });

  // ⚠ CLAUDE: EN sits at the root, every other language in `lang/`, and that split is what keeps
  // the bundler quiet — both halves matter:
  //   • the dynamic import must not target its OWN directory. `import(\`./${k}.js\`)` makes Vite
  //     warn "Variable imports cannot import their own directory" and give up analyzing it, so the
  //     chunks it should emit become a runtime gamble. Pointing at a SUBdirectory (`./lang/…`) is
  //     the documented fix.
  //   • EN must not live in that subdirectory. It is ALSO imported statically (it is the eager
  //     fallback), and a module that is both statically and dynamically imported triggers
  //     INEFFECTIVE_DYNAMIC_IMPORT — rollup keeps it in the entry chunk, which is correct here but
  //     reported as a defect on every build. Out of `lang/`, the two imports can't overlap.
  // Runtime is unaffected: loadLang('en') returns early (LOADED starts with en), so nothing ever
  // asks for `lang/en.js`.
  const langDir = path.join(outDir, "lang");
  fs.mkdirSync(langDir, { recursive: true });
  for (const k of keys) {
    const dir = k === "en" ? outDir : langDir;
    fs.writeFileSync(path.join(dir, `${k}.js`), `${HEADER}export default {\n${langs[k].join("\n")}\n};\n`, "utf8");
  }

  // Everything else the source exported must keep working, verbatim.
  const languages = extractExport(lines, "LANGUAGES");
  if (!languages) { console.log(`FAIL  ${label} — could not extract LANGUAGES`); return; }
  const extraNames = lines
    .filter((l) => /^export const \w+\s*=/.test(l))
    .map((l) => /^export const (\w+)\s*=/.exec(l)[1])
    .filter((n) => n !== "LANGUAGES");
  const extras = extraNames.map((n) => extractExport(lines, n)).filter(Boolean);

  fs.writeFileSync(path.join(outDir, "index.js"), `${HEADER}
import { useMemo, useState, useEffect } from 'react';
import en from './en.js';

${languages}
${extras.length ? "\n" + extras.join("\n\n") + "\n" : ""}
// English is bundled eagerly — it is the fallback for every missing key in every language.
const LOADED = { en };
const base = en;

// Fetch one language chunk. Idempotent, and safe to call for 'en' or an unknown key.
export async function loadLang(key) {
  if (!key || LOADED[key]) return;
  try {
    LOADED[key] = (await import(\`./lang/\${key}.js\`)).default;
  } catch {
    // Unknown or removed language — English stays in place, nothing to do.
  }
}

// ⚠ CLAUDE: useT MUST return a useMemo-wrapped function. The bare form
//   \`return (key) => ...\` produces a new function every render, which destabilizes
//   every useCallback/useEffect depending on \`t\` → infinite render loop, EMFILE crashes.
//   See CLAUDE-i18n.md → "useT() must memoize". Do not "simplify" this.
//
// ⚠ CLAUDE: the useEffect is what makes a language SWITCH work — the chunk for the newly
//   chosen language does not exist yet, so the first render after the switch falls back to
//   English, then this loads it and re-renders once. Removing it leaves the UI in English
//   until some unrelated state change happens to re-render.
export function useT(langKey) {
  const [, bump] = useState(0);
  const ready = !!LOADED[langKey];
  useEffect(() => {
    if (ready) return undefined;
    let alive = true;
    loadLang(langKey).then(() => { if (alive) bump((v) => v + 1); });
    return () => { alive = false; };
  }, [langKey, ready]);
  return useMemo(() => {
    const lang = LOADED[langKey] || base;
    return (key) => lang[key] ?? base[key] ?? key;
  }, [langKey, ready]);
}

// Non-React callers. Synchronous by contract, so it returns English until the language
// chunk has been loaded (the entry point awaits loadLang before the first render).
export function getT(langKey) {
  const lang = LOADED[langKey] || base;
  return (key) => lang[key] ?? base[key] ?? key;
}
`, "utf8");

  console.log(`SPLIT ${label} — ${keys.length} languages${extras.length ? ` (+${extras.length} extra export${extras.length > 1 ? "s" : ""})` : ""}`);
}

const mainDir = path.resolve(process.argv[2] || ".");
splitApp(mainDir, path.basename(path.resolve(mainDir, "..")));
